const PDFDocument = require('pdfkit');

const generatePoliceHandoverPDF = (item, user, res) => {
  const doc = new PDFDocument({ margin: 50 });

  // Stream PDF directly to Express Response without storing physically
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="Handover_Declaration_${item._id}.pdf"`);
  doc.pipe(res);

  // --- HEADER ---
  doc.rect(0, 0, 612, 85).fill('#800000'); // Maroon Brand Background
  doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica-Bold').text('SRI LANKA SMART LOST & FOUND PORTAL', 0, 25, { align: 'center' });
  doc.fontSize(12).font('Helvetica').text('Official Police Item Handover Declaration Form', 0, 55, { align: 'center' });

  // --- METADATA ---
  doc.fillColor('#000000').moveDown(3);
  doc.fontSize(10).font('Helvetica-Bold').text(`Reference Number: SLFMS-${item._id}`, { align: 'right' });
  doc.fontSize(10).font('Helvetica').text(`Timestamp: ${new Date().toLocaleString()}`, { align: 'right' });
  
  doc.moveDown(2);

  // --- ITEM DETAILS ---
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#800000').text('1. ITEM REPORT METADATA', { underline: true });
  doc.fillColor('#000000').moveDown(0.5);
  
  const details = [
    { label: 'Title:', value: item.title },
    { label: 'Category:', value: item.category },
    { label: 'Network Status:', value: item.status },
    { label: 'Date of Incident:', value: new Date(item.date).toLocaleDateString() },
    { label: 'Geographic Location:', value: `${item.city}, ${item.district}, ${item.province}` },
    { label: 'Provided Description:', value: item.description },
  ];

  details.forEach(detail => {
    doc.fontSize(12).font('Helvetica-Bold').text(detail.label, { continued: true });
    doc.font('Helvetica').text(` ${detail.value}`);
    doc.moveDown(0.5);
  });

  doc.moveDown(1.5);

  // --- POSTER DETAILS ---
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#800000').text('2. REGISTERED INDIVIDUAL DETAILS', { underline: true });
  doc.fillColor('#000000').moveDown(0.5);
  
  doc.fontSize(12).font('Helvetica-Bold').text('Verified Username (Network Poster): ', { continued: true });
  doc.font('Helvetica').text(user.username);
  doc.moveDown(0.5);

  doc.fontSize(12).font('Helvetica-Bold').text('Contact Number Provided: ', { continued: true });
  doc.font('Helvetica').text(item.contactNumber);
  
  doc.moveDown(3);

  // --- LEGAL DECLARATION ---
  doc.fontSize(10).font('Helvetica-Oblique').text(
    'I hereby declare that the information provided above is true and accurate to the best of my knowledge. This document serves as a formal handover receipt generated by the SL-SLFMS network and is strictly for submission to local Sri Lanka Police jurisdictions.',
    { align: 'justify' }
  );

  doc.moveDown(5);

  // --- SIGNATURE BLOCKS ---
  const signatureY = doc.y;

  // Handover Party Signature Line
  doc.moveTo(50, signatureY).lineTo(250, signatureY).stroke();
  doc.fontSize(10).font('Helvetica').text('Signature of Handover Party', 50, signatureY + 10);

  // Station Stamp Line
  doc.moveTo(350, signatureY).lineTo(550, signatureY).stroke();
  doc.text('Police Station Officer Stamp & Signature', 350, signatureY + 10);

  doc.end();
};

module.exports = {
  generatePoliceHandoverPDF
};
